version: 2

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_and_make:
          filters:
            branches:
              ignore:
                - gh-pages
      - release_gh-pages:
          requires:
            - test_and_make 
          filters:
            branches:
              only:
                - master
jobs:
  test_and_make:

    docker:
      - image: circleci/rust:latest-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo
      - restore_cache:
          keys:
            - personal-page-{{ checksum "Cargo.lock" }}
      - restore_cache:
          keys:
            - personal-page-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: rustup self update
      - run: rustup toolchain add nightly
      - run: rustup default nightly
      - run: rustup component add rustfmt-preview --toolchain=nightly
      - run: echo "$(git rev-parse --short HEAD)" > tag.txt
      - run: cargo +nightly fmt --all -- --check
      - run: cargo test --release
      - run: npm run css
      - run: cargo install cargo-web
      - run: cargo web deploy
      - save_cache:
          key: personal-page-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"
            - "~/.rustup"
            - /usr/local/cargo/registry/cache
      - save_cache:
          key: personal-page-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - persist_to_workspace:
          root: .
          paths:
            - target

  release_gh-pages:
    docker:
      - image: circleci/rust:latest-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Push to gh-pages
          command: |
            git config --global user.email "me+ci@ruben.io"
            git config --global user.name "Ruben Paz"

            git clone $CIRCLE_REPOSITORY_URL repo
            cd repo
            git checkout gh-pages
            git rm -fr .
            cd ..

            cp -a target/deploy/. repo/.

            mkdir -p repo/.circleci && cp -a .circleci/. repo/.circleci/.

            cd repo
            git add -A
            git commit -m "Automated deployment: ${CIRCLE_SHA1}" --allow-empty

            git push origin gh-pages
